import type { Movie } from "../recommend/data"

const moviesData: Movie[] = [
  {
    movieId: 1,
    title: "Toy Story (1995)",
    genres: "Adventure|Animation|Children|Comedy|Fantasy",
    year: 1995,
    avgRating: 3.9,
  },
  {
    movieId: 2,
    title: "Jumanji (1995)",
    genres: "Adventure|Children|Fantasy",
    year: 1995,
    avgRating: 3.2,
  },
  {
    movieId: 3,
    title: "Grumpier Old Men (1995)",
    genres: "Comedy|Romance",
    year: 1995,
    avgRating: 3.3,
  },
  {
    movieId: 4,
    title: "Waiting to Exhale (1995)",
    genres: "Comedy|Drama|Romance",
    year: 1995,
    avgRating: 2.9,
  },
  {
    movieId: 5,
    title: "Father of the Bride Part II (1995)",
    genres: "Comedy",
    year: 1995,
    avgRating: 3.0,
  },
  {
    movieId: 6,
    title: "Heat (1995)",
    genres: "Action|Crime|Thriller",
    year: 1995,
    avgRating: 3.9,
  },
  {
    movieId: 7,
    title: "Sabrina (1995)",
    genres: "Comedy|Romance",
    year: 1995,
    avgRating: 3.4,
  },
  {
    movieId: 8,
    title: "Tom and Huck (1995)",
    genres: "Adventure|Children",
    year: 1995,
    avgRating: 2.8,
  },
  {
    movieId: 9,
    title: "Sudden Death (1995)",
    genres: "Action",
    year: 1995,
    avgRating: 3.1,
  },
  {
    movieId: 10,
    title: "GoldenEye (1995)",
    genres: "Action|Adventure|Thriller",
    year: 1995,
    avgRating: 3.5,
  },
  {
    movieId: 11,
    title: "American President, The (1995)",
    genres: "Comedy|Drama|Romance",
    year: 1995,
    avgRating: 3.6,
  },
  {
    movieId: 12,
    title: "Dracula: Dead and Loving It (1995)",
    genres: "Comedy|Horror",
    year: 1995,
    avgRating: 2.5,
  },
  {
    movieId: 13,
    title: "Balto (1995)",
    genres: "Animation|Children",
    year: 1995,
    avgRating: 3.0,
  },
  {
    movieId: 14,
    title: "Nixon (1995)",
    genres: "Drama",
    year: 1995,
    avgRating: 3.8,
  },
  {
    movieId: 15,
    title: "Cutthroat Island (1995)",
    genres: "Action|Adventure|Romance",
    year: 1995,
    avgRating: 2.7,
  },
  {
    movieId: 16,
    title: "Casino (1995)",
    genres: "Crime|Drama",
    year: 1995,
    avgRating: 3.9,
  },
  {
    movieId: 17,
    title: "Sense and Sensibility (1995)",
    genres: "Drama|Romance",
    year: 1995,
    avgRating: 3.9,
  },
  {
    movieId: 18,
    title: "Four Rooms (1995)",
    genres: "Comedy",
    year: 1995,
    avgRating: 3.2,
  },
  {
    movieId: 19,
    title: "Ace Ventura: When Nature Calls (1995)",
    genres: "Comedy",
    year: 1995,
    avgRating: 2.7,
  },
  {
    movieId: 20,
    title: "Money Train (1995)",
    genres: "Action|Comedy|Crime|Drama|Thriller",
    year: 1995,
    avgRating: 2.5,
  },
]

export { type Movie, moviesData as movies }
